const KSD_CHANNELS = [
    // DEPORTES
    { id: "tudn", name: "TUDN", cat: "DEPORTES", source: "cablevision" },
    { id: "tnt-sports", name: "TNT SPORTS", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports-premium", name: "FOX SPORTS PREMIUM", cat: "DEPORTES", source: "cablevision" },
    { id: "tyc-sports", name: "TYC SPORTS", cat: "DEPORTES", source: "cablevision" },
    { id: "movistar-deportes", name: "MOVISTAR DEPORTES", cat: "DEPORTES", source: "cablevision" },
    { id: "movistar-la-liga", name: "MOVISTAR LA LIGA", cat: "DEPORTES", source: "cablevision" },
    { id: "movistar-liga-de-campeones", name: "MOVISTAR LIGA DE CAMPEONES", cat: "DEPORTES", source: "cablevision" },
    { id: "dazn-f1", name: "DAZN F1", cat: "DEPORTES", source: "cablevision" },
    { id: "dazn-la-liga", name: "DAZN LA LIGA", cat: "DEPORTES", source: "cablevision" },
    { id: "bein-sports-extra", name: "BEIN SPORTS EXTRA", cat: "DEPORTES", source: "cablevision" },
    { id: "directv-sports", name: "DIRECTV SPORTS", cat: "DEPORTES", source: "cablevision" },
    { id: "directv-sports-2", name: "DIRECTV SPORTS 2", cat: "DEPORTES", source: "cablevision" },
    { id: "directv-sports-plus", name: "DIRECTV SPORTS PLUS", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-premium", name: "ESPN PREMIUM", cat: "DEPORTES", source: "cablevision" },
    { id: "espn", name: "ESPN", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-2", name: "ESPN 2", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-3", name: "ESPN 3", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-4", name: "ESPN 4", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-5", name: "ESPN 5", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-6", name: "ESPN 6", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-7", name: "ESPN 7", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-mexico", name: "ESPN MEXICO", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-2-mexico", name: "ESPN 2 MEXICO", cat: "DEPORTES", source: "cablevision" },
    { id: "espn-3-mexico", name: "ESPN 3 MEXICO", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-deportes", name: "FOX DEPORTES", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports", name: "FOX SPORTS", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports-2", name: "FOX SPORTS 2", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports-3", name: "FOX SPORTS 3", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports-mexico", name: "FOX SPORTS MEXICO", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports-2-mexico", name: "FOX SPORTS 2 MEXICO", cat: "DEPORTES", source: "cablevision" },
    { id: "fox-sports-3-mexico", name: "FOX SPORTS 3 MEXICO", cat: "DEPORTES", source: "cablevision" },

    // TV ABIERTA
    { id: "telefe", name: "TELEFE", cat: "TV ABIERTA", source: "cablevision" },
    { id: "el-trece", name: "EL TRECE", cat: "TV ABIERTA", source: "cablevision" },
    { id: "telemundo-51", name: "TELEMUNDO 51", cat: "TV ABIERTA", source: "cablevision" },
    { id: "telemundo-puerto-rico", name: "TELEMUNDO PUERTO RICO", cat: "TV ABIERTA", source: "cablevision" },
    { id: "univision", name: "UNIVISION", cat: "TV ABIERTA", source: "cablevision" },
    { id: "pasiones", name: "PASIONES", cat: "TV ABIERTA", source: "cablevision" },
    { id: "caracol", name: "CARACOL", cat: "TV ABIERTA", source: "cablevision" },
    { id: "rcn", name: "RCN", cat: "TV ABIERTA", source: "cablevision" },
    { id: "latina", name: "LATINA", cat: "TV ABIERTA", source: "cablevision" },
    { id: "america-tv", name: "AMERICA TV", cat: "TV ABIERTA", source: "cablevision" },
    { id: "atv", name: "ATV", cat: "TV ABIERTA", source: "cablevision" },
    { id: "las-estrellas", name: "LAS ESTRELLAS", cat: "TV ABIERTA", source: "cablevision" },
    { id: "tlnovelas", name: "TLNOVELAS", cat: "TV ABIERTA", source: "cablevision" },
    { id: "galavision", name: "GALAVISION", cat: "TV ABIERTA", source: "cablevision" },
    { id: "azteca-7", name: "AZTECA 7", cat: "TV ABIERTA", source: "cablevision" },
    { id: "azteca-uno", name: "AZTECA UNO", cat: "TV ABIERTA", source: "cablevision" },
    { id: "canal-5", name: "CANAL 5", cat: "TV ABIERTA", source: "cablevision" },

    // INFANTIL
    { id: "cartoon-network", name: "CARTOON NETWORK", cat: "INFANTIL", source: "cablevision" },
    { id: "tooncast", name: "TOONCAST", cat: "INFANTIL", source: "cablevision" },
    { id: "disney-channel", name: "DISNEY CHANNEL", cat: "INFANTIL", source: "cablevision" },
    { id: "nick", name: "NICK", cat: "INFANTIL", source: "cablevision" },

    // CULTURA
    { id: "discovery-channel", name: "DISCOVERY CHANNEL", cat: "CULTURA", source: "cablevision" },
    { id: "history", name: "HISTORY", cat: "CULTURA", source: "cablevision" },
    { id: "history-2", name: "HISTORY 2", cat: "CULTURA", source: "cablevision" },
    { id: "animal-planet", name: "ANIMAL PLANET", cat: "CULTURA", source: "cablevision" },
    { id: "nat-geo", name: "NAT GEO", cat: "CULTURA", source: "cablevision" },
    { id: "discovery-world", name: "DISCOVERY WORLD", cat: "CULTURA", source: "cablevision" },

    // CINE
    { id: "universal-channel", name: "UNIVERSAL CHANNEL", cat: "CINE", source: "cablevision" },
    { id: "tnt", name: "TNT", cat: "CINE", source: "cablevision" },
    { id: "tnt-series", name: "TNT SERIES", cat: "CINE", source: "cablevision" },
    { id: "star-channel", name: "STAR CHANNEL", cat: "CINE", source: "cablevision" },
    { id: "cinemax", name: "CINEMAX", cat: "CINE", source: "cablevision" },
    { id: "space", name: "SPACE", cat: "CINE", source: "cablevision" },
    { id: "syfy", name: "SYFY", cat: "CINE", source: "cablevision" },
    { id: "warner-bros-tv", name: "WARNER CHANNEL", cat: "CINE", source: "cablevision" },
    { id: "warner-bros-tv-mexico", name: "WARNER CHANNEL MX", cat: "CINE", source: "cablevision" },
    { id: "cinecanal", name: "CINECANAL", cat: "CINE", source: "cablevision" },
    { id: "fx", name: "FX", cat: "CINE", source: "cablevision" },
    { id: "axn", name: "AXN", cat: "CINE", source: "cablevision" },
    { id: "amc", name: "AMC", cat: "CINE", source: "cablevision" },
    { id: "studio-universal", name: "STUDIO UNIVERSAL", cat: "CINE", source: "cablevision" },
    { id: "golden-plus", name: "GOLDEN PLUS", cat: "CINE", source: "cablevision" },
    { id: "golden-edge", name: "GOLDEN EDGE", cat: "CINE", source: "cablevision" },
    { id: "golden-premier", name: "GOLDEN PREMIER", cat: "CINE", source: "cablevision" },
    { id: "golden-premier-2", name: "GOLDEN PREMIER 2", cat: "CINE", source: "cablevision" },
    { id: "multipremier", name: "MULTIPREMIER", cat: "CINE", source: "cablevision" },
    { id: "canal-sony", name: "CANAL SONY", cat: "CINE", source: "cablevision" },
    { id: "extrema-tv", name: "EXTREMA TV", cat: "CINE", source: "cablevision" },
    { id: "distrito-comedia", name: "DISTRITO COMEDIA", cat: "CINE", source: "cablevision" }
];
